services:
  db:
    image: postgres:15-alpine
    container_name: ensemble-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ensemble
      POSTGRES_USER: ensemble
      POSTGRES_PASSWORD: ensemble
    volumes:
      - ensemble-data:/var/lib/postgresql/data

volumes:
  ensemble-data:
